# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de1143210a86021837b87c2a95d59cdf6b8c2b718e561ed6edd8eb2765c73236b19edc64ff46fa093799842549cebaea36f5af914cdf05b0436a4071b939b3bd

test:
  secret_key_base: d4d17a37909b5cabc33981017033384777788f68169f446a2089866f196cf8a5811a24db2c9157c2f118fb931ca86324dc12c63cc8bd8943ffa12070130069d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
